### ISSUE TITLE
Error on Safari & IE11

### ISSUE THREAD

**Issue by JumpingJackFly** [elfalem/Leaflet.curve#7]
Hi,

First, thanks a lot for this great lib for Leaflet. I integrated it into my project and it works great. 

I only have a browser compatibility issue with Safari (here version 10.0.3). It looks that some (SVG?) features are not natively supported. While drawing curve on amp, I get the following error:

Leaflet.curve:l182
> TypeError: path.animate is not a function. (In 'path.animate([
						{strokeDashoffset: length},
						{strokeDashoffset: 0}
					], layer.options.animate)', 'path.animate' is undefined)

Any idea how to fix/workaround it?

Olivier

**Comment by elfalem** [comment]
Unfortunately, this is because the Web Animations API is [not supported](http://caniuse.com/#feat=web-animation) in Safari.

As a workaround, I'd suggest using [this](https://github.com/web-animations/web-animations-js) JavaScript implementation of the API. It allows use of the animations API in browsers that don't natively support it (Safari, IE, etc...) while falling back to the native browser implementation when it exists (Firefox, Chrome).

I've not personally tested it so please let me know your experience if you try it.

**Comment by JumpingJackFly** [comment]
Hi,

Thanks for your prompt feedback and I confirm this does not work on IE11 too.

If I test the workaround, I'll let you know.

**Comment by ikrav4ic** [comment]
Hi faipassa
Have you find something to fix it?

**Comment by hermionewy** [comment]
I included the web-animations API and it works on Safari, but the curve shows up without animation. Has anyone figured out how to create smooth animation with this library?
 <script src="https://rawgit.com/web-animations/web-animations-js/master/web-animations.min.js"></script>

**Comment by JumpingJackFly** [comment]
Hi,
No I did not. I finally went for simple L.polyline() as fallback. Here snippet of code i use: [link](https://gist.github.com/faipassa/d23580b8f46cf27839af226b1a48a326)

**Comment by TobiasGruberAT** [comment]
@hermionewy Hey, hope this isn't too late, but how did you include the Web-Animations API?
And did it work without any problems in Safari and IE? :)

**Comment by elfalem** [comment]
It looks like Web Animations support has made it to the Technology Preview version of Safari. Hopefully, it will make it to the stable version soon.
