### ISSUE TITLE
Huge CPU Usage when zoomed in

### ISSUE THREAD

**Issue by desile** [elfalem/Leaflet.curve#8]
Hello! 
I ran into this problem when tried to zoom map.
For example - your demo http://elfalem.github.io/Leaflet.curve/
Zoom in animated curve with dashes until animation became slow and the browser starts to hang.
It happens not only with animated curves but with simple curves with dashes.

**Comment by elfalem** [comment]
Hello!
Can you provide more details about your environment.
* What hardware (model, CPU, RAM), operating system, and browser are you seeing the issue on?
* To what level are you zoomed in when you start seeing the issue?
* Is the issue limited to curves with animations and/or dashes only or does it happen with non-animated curves with solid lines?
* Are you able to quantify the CPU usage (it jumps from __% usage to __% usage)?

**Comment by spmsupun** [comment]
@elfalem Close this

**Comment by jayli3n** [comment]
> @elfalem Close this

This is still an issue I wonder why it was closed, if you zoom in to an animated line close enough, it lags a whole lot :(
Can test it with the demo project: http://elfalem.github.io/Leaflet.curve/

**Comment by jayli3n** [comment]
After some more testing, the lag ONLY occurs to dashed lines, whether animation is turned on or off does not affect CPU usage.
It seems to be related to the way the dashed lines are generated.

**Comment by jayli3n** [comment]
After some more testing, the lag stems from the fact that if you zoom into the map, the distance between point A and point B gets larger in terms of pixels, it then has to create more little dashed lines to cover the increased distance between point A and point B (since the length of each dash is constant).

Tested it with the code in this PR: https://github.com/elfalem/Leaflet.curve/pull/54
Instead of creating more little dashed lines, the PR keeps the number of dashed lines constant and makes each dashed line longer instead to cover the increased distance between point A and point B.

It will look like this now when zoomed in:

![image](https://user-images.githubusercontent.com/44139980/222657661-243f30b7-2291-47b9-aa95-5bcb31d117a6.png)

The PR fixes the lag, but makes the dashed lines look stretched out and weird. The lag is actually still there IF you create the line while you are already zoomed in.

**Comment by jayli3n** [comment]
Created a PR https://github.com/elfalem/Leaflet.curve/pull/57 to potentially fix this.
